// Code generated by "stringer -type=tokType"; DO NOT EDIT.

package jmespath

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[tUnknown-0]
	_ = x[tStar-1]
	_ = x[tDot-2]
	_ = x[tFilter-3]
	_ = x[tFlatten-4]
	_ = x[tLparen-5]
	_ = x[tRparen-6]
	_ = x[tLbracket-7]
	_ = x[tRbracket-8]
	_ = x[tLbrace-9]
	_ = x[tRbrace-10]
	_ = x[tOr-11]
	_ = x[tPipe-12]
	_ = x[tNumber-13]
	_ = x[tUnquotedIdentifier-14]
	_ = x[tQuotedIdentifier-15]
	_ = x[tComma-16]
	_ = x[tColon-17]
	_ = x[tPlus-18]
	_ = x[tMinus-19]
	_ = x[tMultiply-20]
	_ = x[tDivide-21]
	_ = x[tModulo-22]
	_ = x[tDiv-23]
	_ = x[tLT-24]
	_ = x[tLTE-25]
	_ = x[tGT-26]
	_ = x[tGTE-27]
	_ = x[tEQ-28]
	_ = x[tNE-29]
	_ = x[tJSONLiteral-30]
	_ = x[tStringLiteral-31]
	_ = x[tCurrent-32]
	_ = x[tExpref-33]
	_ = x[tAnd-34]
	_ = x[tNot-35]
	_ = x[tEOF-36]
}

const _tokType_name = "tUnknowntStartDottFiltertFlattentLparentRparentLbrackettRbrackettLbracetRbracetOrtPipetNumbertUnquotedIdentifiertQuotedIdentifiertCommatColontPlustMinustMultiplytDividetModulotDivtLTtLTEtGTtGTEtEQtNEtJSONLiteraltStringLiteraltCurrenttExpreftAndtNottEOF"

var _tokType_index = [...]uint8{0, 8, 13, 17, 24, 32, 39, 46, 55, 64, 71, 78, 81, 86, 93, 112, 129, 135, 141, 146, 152, 161, 168, 175, 179, 182, 186, 189, 193, 196, 199, 211, 225, 233, 240, 244, 248, 252}

func (i tokType) String() string {
	if i < 0 || i >= tokType(len(_tokType_index)-1) {
		return "tokType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _tokType_name[_tokType_index[i]:_tokType_index[i+1]]
}
