name: ci

on:
  push:
  pull_request:
jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - 1.18
          - 1.17
          - 1.16
          - 1.15
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install deps 
        run: go mod download
      - name: Tests
        run: make test
      - name: Install golint
        if: ${{ matrix.go-version == '1.17' }}
        run: |
          make install-dev-cmds
          make check
